### PR TITLE
Updated for swift 3

### PR DESCRIPTION
**Pull request by RishabhTayal**

### CODE REVIEW

**Comment by BalestraPatrick** [comment]
Hey, sorry for the delay. This looks great! Could you please open a PR so we can merge this your branch into the [swift3](https://github.com/BalestraPatrick/ValueStepper/tree/swift3) branch? I would like to keep two separate branches and when Swift 3 will be out of beta I will merge it into master. 👍

**Comment by RishabhTayal** [comment]
@BalestraPatrick Will do. That's what I meant to do but since there was no `swift3` branch.

**Comment by RishabhTayal** [comment]
@BalestraPatrick By the way do you know if github lets me create a new branch on your repo when I create a PR?

**Comment by BalestraPatrick** [comment]
If you don't have write access I don't think you can create a new branch on my repo. I will check it out in the new branch and merge it :)

**Pull request closed without merging**
